"""empty message

Revision ID: 0f7eeccf13b9
Revises: 160b8a865dc1
Create Date: 2025-03-25 19:55:42.632569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f7eeccf13b9'
down_revision = '160b8a865dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.alter_column('job_state',
               existing_type=postgresql.BYTEA(),
               nullable=True)
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)
        batch_op.alter_column('job_state',
               existing_type=postgresql.BYTEA(),
               nullable=False)

    # ### end Alembic commands ###
