"""added rating and message to feedback table

Revision ID: 174638fc221e
Revises: 6ca9c01e5241
Create Date: 2025-03-17 09:57:48.048497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174638fc221e'
down_revision = '6ca9c01e5241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('message')
        batch_op.drop_column('rating')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
