"""Update association table foreign keys to bigint

Revision ID: 22177b6a5c93
Revises: 689f80a47d36
Create Date: 2025-03-25 09:43:38.749882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22177b6a5c93'
down_revision = '689f80a47d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_items', schema=None) as batch_op:
        batch_op.alter_column('keyword_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_items', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('keyword_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
