"""changed size of postal code and location_country

Revision ID: 3381be6b108a
Revises: d2f8297377b2
Create Date: 2025-03-18 11:51:39.192344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3381be6b108a'
down_revision = 'd2f8297377b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('location_country',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=2),
               existing_nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('location_country',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
