"""Convert query_id to UUID type

Revision ID: 6013be74f177
Revises: 6ca3c2d7d72f
Create Date: 2025-03-23 20:59:19.495122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6013be74f177'
down_revision = '6ca3c2d7d72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_queries', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='query_id::uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_queries', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
