"""Convert keyword_id to bigserial

Revision ID: 689f80a47d36
Revises: 232cff995d63
Create Date: 2025-03-25 09:30:02.902209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689f80a47d36'
down_revision = '232cff995d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.alter_column('keyword_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.alter_column('keyword_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
