"""added current_bid info

Revision ID: 6ca3c2d7d72f
Revises: 3381be6b108a
Create Date: 2025-03-19 15:09:06.011238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca3c2d7d72f'
down_revision = '3381be6b108a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_bid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_bid_currency', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('current_bid_currency')
        batch_op.drop_column('current_bid')

    # ### end Alembic commands ###
