"""add optional keyword filters to item relevance

Revision ID: 6ca9c01e5241
Revises: dbd47fa2b01e
Create Date: 2025-03-14 19:18:02.286753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca9c01e5241'
down_revision = 'dbd47fa2b01e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_item_relevance_feedback')
    with op.batch_alter_table('item_relevance_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_keywords', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('excluded_keywords', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_relevance_feedback', schema=None) as batch_op:
        batch_op.drop_column('excluded_keywords')
        batch_op.drop_column('required_keywords')

    op.create_table('_alembic_tmp_item_relevance_feedback',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('keyword_id', sa.INTEGER(), nullable=False),
    sa.Column('is_relevant', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('simple_hybrid_levenshtein_confidence', sa.FLOAT(), nullable=True),
    sa.Column('cosine_similarity', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.keyword_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', 'keyword_id', name='uq_user_item_keyword_feedback')
    )
    # ### end Alembic commands ###
