"""Fix query_id type in user_query_items

Revision ID: 9f21b5e3701a
Revises: 9916e43e89d0
Create Date: 2025-03-23 21:18:58.920207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f21b5e3701a'
down_revision = '9916e43e89d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    with op.batch_alter_table('user_queries', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))

    with op.batch_alter_table('user_query_items', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_query_items', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('user_queries', schema=None) as batch_op:
        batch_op.alter_column('query_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(gen_random_uuid())'))

    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    # ### end Alembic commands ###
