"""removed email verification steps will add later

Revision ID: c8d355d86e44
Revises: 3c4009c47af2
Create Date: 2025-03-17 15:58:08.167538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d355d86e44'
down_revision = '3c4009c47af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verification_token_expiration')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token_expiration', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
