"""added grace period to stripe subscription

Revision ID: d2f8297377b2
Revises: a8fb6ffcf059
Create Date: 2025-03-18 10:38:10.920395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f8297377b2'
down_revision = 'a8fb6ffcf059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grace_period_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_failure_start', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('payment_failure_start')
        batch_op.drop_column('grace_period_end')

    # ### end Alembic commands ###
